### ISSUE TITLE
Move to curveball.js.org

### ISSUE THREAD

**Issue by jeanlucaslima** [curveball/website#6]
The process to get a `js.org` URL is quite simple and the URL fits the project pretty well.

**Comment by evert** [comment]
I think it might be nice to have this as a second alternative domain, but it feels a bit safer to stick to our own domain we own .. i thought that js.org might have been from FSF when I first heard about it. We gotta have something that we still control if we are sick of github pages, if we want to host other services, or if the owner of js.org forgot to renew their domain =)

**Comment by jeanlucaslima** [comment]
Yes, good point. They do indeed have a good governance (and open [finance](https://opencollective.com/js-org)). But it is not taken care by the FSF or OpenJSFoundation (which is part of the Linux Foundation). 

Will close this for now.
